import React, { useState, useEffect, useCallback, useRef } from 'react';
import './App.css';

// --- API Helper ---
const api = {
  async request(endpoint, options = {}) {
    const { body, ...customConfig } = options;
    const headers = { 'Content-Type': 'application/json' };
    const token = localStorage.getItem('token');
    if (token) { headers['Authorization'] = `Bearer ${token}`; }
    const config = { method: body ? 'POST' : 'GET', ...customConfig, headers: { ...headers, ...customConfig.headers } };
    if (body) { config.body = JSON.stringify(body); }
    const response = await fetch(`http://localhost:8080/api${endpoint}`, config);
    if (!response.ok) {
        const errorText = await response.text();
        throw new Error(errorText || `Request failed with status ${response.status}`); 
    }
    const contentType = response.headers.get("content-type");
    if (contentType && contentType.indexOf("application/json") !== -1) {
        return response.json();
    }
    return null;
  },
  login: (email, password) => api.request('/auth/login', { body: { email, password } }),
  register: (fullName, email, password, role) => api.request('/auth/register', { body: { fullName, email, password, role } }),
  getInternships: () => api.request('/internships/all'),
  postInternship: (internshipData) => api.request('/internships/post', { body: internshipData }),
  getRecruiterPostings: () => api.request('/internships/my-postings'),
  getAllUsers: () => api.request('/admin/users'),
  deleteUser: (userId) => api.request(`/admin/users/${userId}`, { method: 'DELETE' }),
  updateUser: (userId, userData) => api.request(`/admin/users/${userId}`, { method: 'PUT', body: userData }),
  getAnalytics: () => api.request('/admin/analytics'),
  getStudentProfile: () => api.request('/student/profile'),
  createOrUpdateStudentProfile: (profileData) => api.request('/student/profile', { body: profileData }),
  applyForInternship: (internshipId) => api.request(`/internships/${internshipId}/apply`, { method: 'POST' }),
  getApplicants: (internshipId) => api.request(`/internships/${internshipId}/applicants`),
};

// --- Reusable UI Components ---
const Header = ({ user, onLogout }) => ( <header className="header"><div className="header-content"><h1 className="logo"><span className="logo-intern">Intern</span>Zilla</h1>{user && (<div className="user-info"><span>Welcome, {user.fullName}</span><button onClick={onLogout} className="button logout-button">Logout</button></div>)}</div></header> );
const DashboardCard = ({ title, description, onClick }) => ( <div className="dashboard-card-link" onClick={onClick}><div className="dashboard-card"><h3>{title}</h3><p>{description}</p></div></div> );

// --- Auth Components ---
const AuthPage = ({ onLogin }) => { const [isLogin, setIsLogin] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const handleRegisterSuccess = () => { setIsLogin(true); setSuccess('Registration successful! Please login.'); setError(''); }; return ( <div className="auth-page"><div className="auth-card"><h2 className="auth-title"><span className="logo-intern">Intern</span>Zilla</h2><p className="auth-subtitle">{isLogin ? 'Welcome Back!' : 'Create Your Account'}</p>{error && <p className="error-message">{error}</p>}{success && <p className="success-message">{success}</p>}{isLogin ? <LoginForm onLogin={onLogin} setError={setError} /> : <RegisterForm onRegisterSuccess={handleRegisterSuccess} setError={setError} />}<p className="toggle-auth">{isLogin ? "Don't have an account?" : 'Already have an account?'}<button onClick={() => { setIsLogin(!isLogin); setError(''); setSuccess(''); }} className="toggle-auth-button">{isLogin ? 'Sign Up' : 'Login'}</button></p></div></div> ); };
const LoginForm = ({ onLogin, setError }) => { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [isLoading, setIsLoading] = useState(false); const handleSubmit = async (e) => { e.preventDefault(); setError(''); setIsLoading(true); try { const data = await api.login(email, password); onLogin(data.jwt); } catch (err) { setError(err.message); } finally { setIsLoading(false); } }; return ( <form onSubmit={handleSubmit}><div className="form-group"><label htmlFor="login-email">Email Address</label><input type="email" id="login-email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><div className="form-group"><label htmlFor="login-password">Password</label><input type="password" id="login-password" value={password} onChange={(e) => setPassword(e.target.value)} required /></div><button type="submit" className="button auth-button" disabled={isLoading}>{isLoading ? 'Logging in...' : 'Login'}</button></form> ); };
const RegisterForm = ({ onRegisterSuccess, setError }) => { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [fullName, setFullName] = useState(''); const [role, setRole] = useState('STUDENT'); const [isLoading, setIsLoading] = useState(false); const handleSubmit = async (e) => { e.preventDefault(); setError(''); setIsLoading(true); try { await api.register(fullName, email, password, role); onRegisterSuccess(); } catch (err) { setError(err.message); } finally { setIsLoading(false); } }; return ( <form onSubmit={handleSubmit}><div className="form-group"><label htmlFor="reg-fullName">Full Name</label><input type="text" id="reg-fullName" value={fullName} onChange={(e) => setFullName(e.target.value)} required /></div><div className="form-group"><label htmlFor="reg-email">Email Address</label><input type="email" id="reg-email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><div className="form-group"><label htmlFor="reg-password">Password</label><input type="password" id="reg-password" value={password} onChange={(e) => setPassword(e.target.value)} required /></div><div className="form-group"><label htmlFor="role">I am a:</label><select id="role" value={role} onChange={(e) => setRole(e.target.value)}><option value="STUDENT">Student</option><option value="RECRUITER">Recruiter</option></select></div><button type="submit" className="button auth-button" disabled={isLoading}>{isLoading ? 'Signing up...' : 'Sign Up'}</button></form> ); };

// --- Page & Dashboard Components ---

const AdminDashboard = ({ onNavigate }) => ( <div><h2 className="dashboard-title">Admin Dashboard</h2><div className="dashboard-grid"><DashboardCard title="Manage Users" description="View, edit, or remove user accounts." onClick={() => onNavigate('MANAGE_USERS')} /><DashboardCard title="View All Internships" description="Monitor all internship postings." onClick={() => onNavigate('VIEW_INTERNSHIPS')} /><DashboardCard title="Platform Analytics" description="Check statistics on user activity." onClick={() => onNavigate('ANALYTICS')} /></div></div> );
const ManageUsers = ({ onBack }) => { const [users, setUsers] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editingUser, setEditingUser] = useState(null); const fetchUsers = useCallback(async () => { try { setError(''); setLoading(true); const data = await api.getAllUsers(); setUsers(data); } catch (err) { setError('Could not fetch users.'); } finally { setLoading(false); } }, []); useEffect(() => { fetchUsers(); }, [fetchUsers]); const handleDelete = async (userId) => { if (window.confirm('Are you sure you want to delete this user?')) { try { await api.deleteUser(userId); fetchUsers(); } catch (err) { setError('Failed to delete user.'); } } }; const handleUpdate = async () => { await fetchUsers(); setEditingUser(null); }; if (loading) return <div className="loading"></div>; return ( <div>{editingUser && <EditUserModal user={editingUser} onClose={() => setEditingUser(null)} onUpdate={handleUpdate} />}<button onClick={onBack} className="button back-button">&larr; Back to Dashboard</button><h2 className="dashboard-title">Manage Users</h2>{error && <p className="error-message">{error}</p>}<div className="dashboard-card"><table className="user-table"><thead><tr><th>ID</th><th>Full Name</th><th>Email</th><th>Role</th><th>Actions</th></tr></thead><tbody>{users.map(user => (<tr key={user.id}><td>{user.id}</td><td>{user.fullName}</td><td>{user.email}</td><td>{user.role}</td><td className="actions-cell"><button className="button button-edit" onClick={() => setEditingUser(user)}>Edit</button><button className="button button-remove" onClick={() => handleDelete(user.id)}>Remove</button></td></tr>))}</tbody></table></div></div> ); };
const EditUserModal = ({ user, onClose, onUpdate }) => { const [fullName, setFullName] = useState(user.fullName); const [role, setRole] = useState(user.role); const [error, setError] = useState(''); const [isLoading, setIsLoading] = useState(false); const handleSave = async (e) => { e.preventDefault(); setError(''); setIsLoading(true); try { await api.updateUser(user.id, { fullName, role }); onUpdate(); } catch (err) { setError('Failed to update user.'); } finally { setIsLoading(false); } }; return ( <div className="modal-overlay"><div className="modal-content"><h3 className="form-title">Edit User</h3><form onSubmit={handleSave}><div className="form-group"><label>Full Name</label><input type="text" value={fullName} onChange={e => setFullName(e.target.value)} required /></div><div className="form-group"><label>Email (cannot be changed)</label><input type="email" value={user.email} disabled /></div><div className="form-group"><label>Role</label><select value={role} onChange={e => setRole(e.target.value)}><option value="STUDENT">Student</option><option value="RECRUITER">Recruiter</option><option value="ADMIN">Admin</option></select></div>{error && <p className="error-message">{error}</p>}<div className="modal-actions"><button type="button" className="button button-secondary" onClick={onClose}>Cancel</button><button type="submit" className="button auth-button" disabled={isLoading}>{isLoading ? 'Saving...' : 'Save Changes'}</button></div></form></div></div> ); };
const ViewAllInternships = ({ onBack }) => { const [internships, setInternships] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { const fetchInternships = async () => { try { setLoading(true); const data = await api.getInternships(); setInternships(data); } catch (err) { setError('Could not fetch internships.'); } finally { setLoading(false); } }; fetchInternships(); }, []); if (loading) return <div className="loading"></div>; if (error) return <p className="error-message">{error}</p>; return ( <div> <button onClick={onBack} className="button back-button">&larr; Back to Dashboard</button> <h2 className="dashboard-title">All Internship Postings</h2> <div className="internship-list">{internships.length > 0 ? internships.map(internship => ( <div key={internship.id} className="internship-card"><div className="internship-details"><h3 className="internship-title">{internship.title}</h3><p className="internship-meta">Recruiter ID: {internship.recruiterId} | Stipend: {internship.stipend || 'N/A'} | Type: {internship.internshipType}</p></div><button className="button button-remove">Remove</button></div> )) : <div className="dashboard-card empty-state"><h3>No Internships Found</h3><p>There are no internships posted on the platform yet.</p></div>}</div></div> ); };
const PlatformAnalytics = ({ onBack }) => { const [stats, setStats] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const chartRef = useRef(null); useEffect(() => { const fetchStats = async () => { try { setLoading(true); const data = await api.getAnalytics(); setStats(data); } catch (err) { setError('Could not fetch platform analytics.'); } finally { setLoading(false); } }; fetchStats(); }, []); useEffect(() => { let chartInstance = null; if (stats && chartRef.current) { const chartContext = chartRef.current.getContext('2d'); chartInstance = new window.Chart(chartContext, { type: 'bar', data: { labels: ['Students', 'Recruiters'], datasets: [{ label: 'User Roles', data: [stats.totalStudents, stats.totalRecruiters], backgroundColor: ['rgba(79, 70, 229, 0.8)', 'rgba(245, 158, 11, 0.8)'], borderColor: ['rgba(79, 70, 229, 1)', 'rgba(245, 158, 11, 1)'], borderWidth: 1 }] }, options: { scales: { y: { beginAtZero: true, ticks: { stepSize: 1 } } }, responsive: true, maintainAspectRatio: false } }); } return () => { if (chartInstance) { chartInstance.destroy(); } }; }, [stats]); if (loading) return <div className="loading"></div>; if (error) return <p className="error-message">{error}</p>; return ( <div> <button onClick={onBack} className="button back-button">&larr; Back to Dashboard</button> <h2 className="dashboard-title">Platform Analytics</h2> <div className="analytics-grid"><div className="stat-card"><h3>Total Users</h3><p className="stat-number">{stats?.totalUsers}</p></div><div className="stat-card"><h3>Total Internships</h3><p className="stat-number">{stats?.totalInternships}</p></div></div> <div className="dashboard-card chart-card"><h3>User Distribution</h3><div className="chart-container"><canvas ref={chartRef}></canvas></div></div> </div> ); };
const RecruiterDashboard = ({ onNavigate }) => ( <div><h2 className="dashboard-title">Recruiter Dashboard</h2><div className="dashboard-grid"><DashboardCard title="Post a New Internship" description="Create and post new internship opportunities." onClick={() => onNavigate('POST_FORM')} /><DashboardCard title="View Your Postings" description="Manage your existing internship posts." onClick={() => onNavigate('VIEW_POSTINGS')} /></div></div> );
const PostInternshipForm = ({ onBack }) => { const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [stipend, setStipend] = useState(''); const [internshipType, setInternshipType] = useState('ONLINE'); const [eligibilityCriteria, setEligibilityCriteria] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [isLoading, setIsLoading] = useState(false); const handleSubmit = async (e) => { e.preventDefault(); setError(''); setSuccess(''); setIsLoading(true); try { await api.postInternship({ title, description, stipend, internshipType, eligibilityCriteria }); setSuccess('Internship posted successfully!'); setTitle(''); setDescription(''); setStipend(''); setInternshipType('ONLINE'); setEligibilityCriteria(''); } catch (err) { setError(err.message); } finally { setIsLoading(false); } }; return ( <div> <button onClick={onBack} className="button back-button">&larr; Back to Dashboard</button> <h2 className="dashboard-title">Post a New Internship</h2> <div className="dashboard-card form-card"><form onSubmit={handleSubmit}><div className="form-group"><label htmlFor="title">Internship Title</label><input id="title" type="text" value={title} onChange={e => setTitle(e.target.value)} required /></div><div className="form-group"><label htmlFor="description">Description</label><textarea id="description" value={description} onChange={e => setDescription(e.target.value)} required rows="4"></textarea></div><div className="form-group"><label htmlFor="stipend">Stipend (e.g., $2000/month)</label><input id="stipend" type="text" value={stipend} onChange={e => setStipend(e.target.value)} /></div><div className="form-group"><label htmlFor="eligibility">Eligibility Criteria</label><input id="eligibility" type="text" value={eligibilityCriteria} onChange={e => setEligibilityCriteria(e.target.value)} /></div><div className="form-group"><label htmlFor="type">Internship Type</label><select id="type" value={internshipType} onChange={e => setInternshipType(e.target.value)}><option value="ONLINE">Online</option><option value="OFFLINE">Offline</option><option value="HYBRID">Hybrid</option></select></div>{error && <p className="error-message">{error}</p>}{success && <p className="success-message">{success}</p>}<button type="submit" className="button auth-button" disabled={isLoading}>{isLoading ? 'Posting...' : 'Post Internship'}</button></form></div> </div> ); };
const ApplicantsModal = ({ internship, onClose }) => { const [applicants, setApplicants] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const formatResumeUrl = (url) => { if (!url) return '#'; let trimmedUrl = url.trim(); if (trimmedUrl.startsWith('http://') || trimmedUrl.startsWith('https://')) { return trimmedUrl; } return `https://${trimmedUrl}`; }; useEffect(() => { const fetchApplicants = async () => { try { setLoading(true); const data = await api.getApplicants(internship.id); setApplicants(data); } catch (err) { setError('Could not fetch applicants.'); } finally { setLoading(false); } }; fetchApplicants(); }, [internship.id]); return ( <div className="modal-overlay"><div className="modal-content"><h3 className="form-title">Applicants for "{internship.title}"</h3>{loading ? <div className="loading"></div> : error ? <p className="error-message">{error}</p> : applicants.length === 0 ? <div className="empty-state"><h3>No Applicants Yet</h3><p>Check back later to see who has applied.</p></div> : ( <table className="user-table"><thead><tr><th>Name</th><th>Email</th><th>CGPA</th><th>Skills</th><th>Resume</th></tr></thead><tbody>{applicants.map(app => (<tr key={app.id}><td>{app.fullName}</td><td>{app.email}</td><td>{app.cgpa || 'N/A'}</td><td>{app.skills || 'N/A'}</td><td>{app.resumeUrl ? <a href={formatResumeUrl(app.resumeUrl)} target="_blank" rel="noopener noreferrer">View</a> : 'N/A'}</td></tr>))}</tbody></table> )}<div className="modal-actions"><button className="button button-secondary" onClick={onClose}>Close</button></div></div></div> ); };
const ViewMyPostings = ({ onBack }) => { const [internships, setInternships] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selectedInternship, setSelectedInternship] = useState(null); useEffect(() => { const fetchPostings = async () => { try { setLoading(true); const data = await api.getRecruiterPostings(); setInternships(data); } catch (err) { setError('Could not fetch your internship postings.'); } finally { setLoading(false); } }; fetchPostings(); }, []); if (loading) return <div className="loading"></div>; if (error) return <p className="error-message">{error}</p>; return ( <div>{selectedInternship && <ApplicantsModal internship={selectedInternship} onClose={() => setSelectedInternship(null)} />}<button onClick={onBack} className="button back-button">&larr; Back to Dashboard</button><h2 className="dashboard-title">Your Internship Postings</h2><div className="internship-list">{internships.length > 0 ? internships.map(internship => ( <div key={internship.id} className="internship-card"><div className="internship-details"><h3 className="internship-title">{internship.title}</h3><p className="internship-meta">Stipend: {internship.stipend || 'N/A'} | Type: {internship.internshipType}</p></div><button className="button" onClick={() => setSelectedInternship(internship)}>View Applicants</button></div> )) : <div className="dashboard-card empty-state"><h3>No Postings Found</h3><p>You have not posted any internships yet.</p></div>}</div></div> ); };
const StudentDashboard = () => { const [internships, setInternships] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [applyStatus, setApplyStatus] = useState({}); useEffect(() => { const fetchInternships = async () => { try { setLoading(true); const data = await api.getInternships(); setInternships(data); } catch (err) { setError('Could not fetch internships. Please try again later.'); } finally { setLoading(false); } }; fetchInternships(); }, []); const handleApply = async (internshipId) => { setApplyStatus(prev => ({ ...prev, [internshipId]: 'loading' })); try { await api.applyForInternship(internshipId); setApplyStatus(prev => ({ ...prev, [internshipId]: 'success' })); } catch (err) { setApplyStatus(prev => ({ ...prev, [internshipId]: 'error' })); } }; if (loading) return <div className="loading"></div>; if (error) return <p className="error-message">{error}</p>; return ( <div> <h2 className="dashboard-title">Available Internships</h2> <div className="internship-list">{internships.length > 0 ? internships.map(internship => ( <div key={internship.id} className="internship-card"><div className="internship-details"><h3 className="internship-title">{internship.title}</h3><p className="internship-meta">Stipend: {internship.stipend || 'N/A'} | Type: {internship.internshipType}</p></div><div> <button className="button apply-button" disabled={applyStatus[internship.id] === 'loading' || applyStatus[internship.id] === 'success'} onClick={() => handleApply(internship.id)}> {applyStatus[internship.id] === 'loading' ? 'Applying...' : applyStatus[internship.id] === 'success' ? 'Applied!' : 'Apply'} </button> {applyStatus[internship.id] === 'error' && <div className="error-message" style={{ marginTop: '0.5rem' }}>Could not apply. Try again.</div>}</div></div> )) : <div className="dashboard-card empty-state"><h3>No Internships Available</h3><p>Check back soon for new opportunities!</p></div>}</div> </div> ); };
const CreateProfilePage = ({ onProfileCreated }) => { const [cgpa, setCgpa] = useState(''); const [skills, setSkills] = useState(''); const [resumeUrl, setResumeUrl] = useState(''); const [error, setError] = useState(''); const [isLoading, setIsLoading] = useState(false); const handleSubmit = async (e) => { e.preventDefault(); setError(''); setIsLoading(true); try { await api.createOrUpdateStudentProfile({ cgpa, skills, resumeUrl }); onProfileCreated(); } catch (err) { setError(err.message); } finally { setIsLoading(false); } }; return ( <div className="auth-page"><div className="auth-card"><h2 className="auth-title">Complete Your Profile</h2><p className="auth-subtitle">This information will be visible to recruiters.</p><form onSubmit={handleSubmit} className="auth-form"><div className="form-group"><label htmlFor="cgpa">CGPA</label><input type="number" step="0.01" id="cgpa" value={cgpa} onChange={(e) => setCgpa(e.target.value)} required /></div><div className="form-group"><label htmlFor="skills">Skills (comma-separated)</label><input type="text" id="skills" value={skills} onChange={(e) => setSkills(e.target.value)} required placeholder="e.g., Java, React, SQL" /></div><div className="form-group"><label htmlFor="resumeUrl">Resume URL</label><input type="text" id="resumeUrl" value={resumeUrl} onChange={(e) => setResumeUrl(e.target.value)} required placeholder="www.linkedin.com/in/your-profile" /></div>{error && <p className="error-message">{error}</p>}<button type="submit" className="button auth-button" disabled={isLoading}>{isLoading ? 'Saving...' : 'Save Profile'}</button></form></div></div> ); };

// --- Main App Component ---
function App() {
  const [user, setUser] = useState(null);
  const [token, setToken] = useState(() => localStorage.getItem('token'));
  const [hasProfile, setHasProfile] = useState(true);
  const [isLoadingProfile, setIsLoadingProfile] = useState(true);
  const [currentView, setCurrentView] = useState('DASHBOARD');

  useEffect(() => {
    if (token) {
      try {
        const decodedToken = JSON.parse(atob(token.split('.')[1]));
        const currentUser = { email: decodedToken.sub, fullName: decodedToken.fullName, role: decodedToken.role };
        setUser(currentUser);
        if (currentUser.role === 'STUDENT') {
            setIsLoadingProfile(true);
            api.getStudentProfile().then(() => setHasProfile(true)).catch(() => setHasProfile(false)).finally(() => setIsLoadingProfile(false));
        } else {
            setIsLoadingProfile(false);
        }
      } catch (error) { console.error("Failed to decode JWT:", error); handleLogout(); }
    } else {
      setUser(null);
      setIsLoadingProfile(false);
    }
  }, [token]);

  const handleLogin = (jwt) => { localStorage.setItem('token', jwt); setToken(jwt); setCurrentView('DASHBOARD'); };
  const handleLogout = useCallback(() => { localStorage.removeItem('token'); setToken(null); }, []);
  const handleNavigation = (view) => { setCurrentView(view); };
  const handleProfileCreated = () => { setHasProfile(true); };

  const renderContent = () => {
    if (!user) { return <AuthPage onLogin={handleLogin} />; }
    if (isLoadingProfile) { return <div className="loading"></div>; }
    if (user.role === 'STUDENT' && !hasProfile) { return <CreateProfilePage onProfileCreated={handleProfileCreated} />; }

    switch (user.role) {
      case 'ADMIN':
        if (currentView === 'MANAGE_USERS') return <ManageUsers onBack={() => handleNavigation('DASHBOARD')} />;
        if (currentView === 'VIEW_INTERNSHIPS') return <ViewAllInternships onBack={() => handleNavigation('DASHBOARD')} />;
        if (currentView === 'ANALYTICS') return <PlatformAnalytics onBack={() => handleNavigation('DASHBOARD')} />;
        return <AdminDashboard onNavigate={handleNavigation} />;
      case 'RECRUITER':
        if (currentView === 'POST_FORM') return <PostInternshipForm onBack={() => handleNavigation('DASHBOARD')} />;
        if (currentView === 'VIEW_POSTINGS') return <ViewMyPostings onBack={() => handleNavigation('DASHBOARD')} />;
        return <RecruiterDashboard onNavigate={handleNavigation} />;
      case 'STUDENT':
        return <StudentDashboard />;
      default:
        return <p>Error: Unknown user role.</p>;
    }
  };

  return (
    <div className="app-wrapper">
      <Header user={user} onLogout={handleLogout} />
      <main className="container">
        {renderContent()}
      </main>
    </div>
  );
}

export default App;