DROP DATABASE IF EXISTS PROJECT1;
CREATE DATABASE PROJECT1;
USE PROJECT1;

-- DROPPING TABLES TO AVOID CONFLICTS
DROP TABLE IF EXISTS APPLICATION;
DROP TABLE IF EXISTS INTERNSHIP;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS COMPANY;
DROP TABLE IF EXISTS RECRUITER;
DROP TABLE IF EXISTS USER;

-- CREATING USER TABLE
CREATE TABLE USER 
(
    USER_ID INT PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE,
    PASSWORD VARCHAR(100),
    ROLE ENUM('ADMIN', 'STUDENT', 'RECRUITER')
);

-- CREATING STUDENT TABLE
CREATE TABLE STUDENT
(
    STUDENT_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

-- CREATING RECRUITER TABLE
CREATE TABLE RECRUITER
(
    RECRUITER_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    COMPANY_NAME VARCHAR(100),
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

-- CREATING COMPANY TABLE
CREATE TABLE COMPANY
(
    COMPANY_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    INDUSTRY VARCHAR(100),
    CONTACT_EMAIL VARCHAR(100),
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

-- CREATING INTERNSHIP TABLE
CREATE TABLE INTERNSHIP
(
    INTERNSHIP_ID INT PRIMARY KEY,
    TITLE VARCHAR(100),
    STIPEND INT,
    DURATION_WEEKS INT,
    MODE ENUM('ONLINE', 'OFFLINE', 'DUAL'),
    COMPANY_ID INT,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(COMPANY_ID)
);

-- CREATING APPLICATION TABLE
CREATE TABLE APPLICATION
(
    APPLICATION_ID INT PRIMARY KEY,
    STUDENT_ID INT,
    INTERNSHIP_ID INT,
    APPLY_DATE DATE,
    STATUS ENUM('APPLIED', 'SELECTED', 'REJECTED'),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (INTERNSHIP_ID) REFERENCES INTERNSHIP(INTERNSHIP_ID)
);

-- INSERTING USERS
INSERT INTO USER VALUES
(1, 'ADMIN', 'ADMIN@321', 'ADMIN'),
(2, 'ASHMIT', 'PASS@321', 'STUDENT'),
(3, 'HR', 'HR@321', 'RECRUITER');

-- INSERTING STUDENT
INSERT INTO STUDENT(STUDENT_ID, NAME, EMAIL, USER_ID)
VALUES (101, 'ASHMIT DESAI', '24104139@apsit.edu.in', 2);

-- INSERTING RECRUITER
INSERT INTO RECRUITER(RECRUITER_ID, NAME, EMAIL, COMPANY_NAME, USER_ID)
VALUES (301, 'HR', 'HR@321', 'TCS', 3);

-- INSERTING COMPANY
INSERT INTO COMPANY(COMPANY_ID, NAME, INDUSTRY, CONTACT_EMAIL, USER_ID)
VALUES (201, 'TCS', 'IT SERVICES', 'hr@gmail.com', 3);

-- INSERTING INTERNSHIPS
INSERT INTO INTERNSHIP(INTERNSHIP_ID, TITLE, STIPEND, DURATION_WEEKS, MODE, COMPANY_ID)
VALUES 
(401, 'WEB DEV', 10000, 4, 'ONLINE', 201),
(402, 'GAME DEV', 11000, 4, 'OFFLINE', 201);

-- INSERTING APPLICATIONS
INSERT INTO APPLICATION(APPLICATION_ID, STUDENT_ID, INTERNSHIP_ID, APPLY_DATE, STATUS)
VALUES 
(501, 101, 401, '2025-07-02', 'APPLIED'),
(502, 101, 402, '2025-07-05', 'SELECTED');

-- VIEW STUDENT’S INTERNSHIPS
SELECT I.TITLE, A.STATUS, A.APPLY_DATE
FROM APPLICATION A
JOIN INTERNSHIP I ON A.INTERNSHIP_ID = I.INTERNSHIP_ID
WHERE A.STUDENT_ID = (
    SELECT STUDENT_ID FROM STUDENT WHERE USER_ID = 2
);

-- VIEW INTERNSHIPS POSTED BY COMPANY
SELECT * FROM INTERNSHIP
WHERE COMPANY_ID = (
    SELECT COMPANY_ID FROM COMPANY WHERE USER_ID = 3
);

-- VIEW WHO APPLIED TO WHICH INTERNSHIP
SELECT S.NAME AS STUDENT, I.TITLE AS INTERNSHIP, A.STATUS
FROM APPLICATION A
JOIN STUDENT S ON A.STUDENT_ID = S.STUDENT_ID
JOIN INTERNSHIP I ON A.INTERNSHIP_ID = I.INTERNSHIP_ID;
